title: "Mi Sitio con Bedomax.com"
description: "Un sitio hecho desde cero con Jekyll"
author: "Bedomax"
baseurl: ""
url: "http://localhost:4000"
permalink: /:title/

sass:
  sass_dir: assets/_sass
  style: expanded

collections:
  pages:
    output: true
    permalink: /:path/