title: "Mi Sitio con Bedomax.com"
description: "Un sitio hecho desde cero con Jekyll"
author: "Bedomax"
baseurl: ""
url: "http://localhost:4000"
permalink: /:title/

sass:
  sass_dir: assets/scss
  style: expanded
  load_paths:
    - _sass
    - node_modules

collections:
  pages:
    output: true
    permalink: /:path/

# Configuración de Bootstrap
bootstrap:
  version: 5.3.0